### ISSUE TITLE
What is the capacity of the hard drive needed?

### ISSUE THREAD

**Issue by DUya98** [cube-network/Cube#20]
Please write the recommended disk size

**Comment by Nanyan** [comment]
The disk space will increase depends on many factors, e.g. the node type( archive or full ), the total transactions count and total accounts, the time you start a fast/snap sync,  etc.
And for full nodes, it can reduce disk space needed by doing prune-state regularly. 

So it's hard to give an estimation.

For a basic recommendation, we think a 1 TB disk space is quite practical for a full node in order to reduce the frequency of maintenance.
